export default {
  1: 'Una persona tiene más de 1.460 sueños al año.',
  2: 'Los egipcios antiguos dormían en almohadas hechas de piedra.',
  3: 'El corazón del erizo late un promedio de 300 veces por minuto.',
  4: 'Los ojos de las abejas tienen un cierto tipo de pelo.',
  5: 'Parpadeamos más de 10.000.000 de veces en un año.',
  6: 'Un hombre llamado Charles Osborne tuvo hipo durante 69 años.',
  7: 'Los búhos son las únicas aves que pueden ver el color azul.',
  8: 'Al nacer tenemos 300 huesos, pero de adulto solo tenemos 206.',
  9: 'Un topo puede cavar un túnel de 100 metros de largo en solo una noche.',
  10: 'El corazón humano late más de 100.000 veces en un día.',
  11: 'Los delfines duermen con un ojo abierto.',
  12: 'Thomas Alba Edison tenía miedo a la oscuridad.',
  13: 'La Tierra pesa alrededor de 6.588.000.000.000.000.000.000.000 toneladas.',
  14: 'Los dientes humanos son casi tan duros como piedras.',
  15: 'La orina del gato brilla bajo la luz ultravioleta.',
  16: 'El elefante es el único mamífero que no puede saltar.',
  17: 'El espermatozoide masculino es la célula más pequeña del cuerpo. En contraposición, el óvulo femenino es la más grande',
  18: 'El polvo que tienes por casa está compuesto en un 90% por células muertas de nuestro cuerpo.',
  19: 'En 30 minutos, el cuerpo humano libera suficiente calor como para hervir casi medio litro de agua.',
  20: 'Más de 1.000 aves mueren anualmente por estrellarse contra ventanas.'
}